# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bs_block <- function(ys, w, freq, band, band_ind, R, B, L, coherency) {
    .Call(`_SpecCp_bs_block`, ys, w, freq, band, band_ind, R, B, L, coherency)
}

bs_consecutive <- function(ys, w, freq, band, band_ind, at, projections, R, L, coherency) {
    .Call(`_SpecCp_bs_consecutive`, ys, w, freq, band, band_ind, at, projections, R, L, coherency)
}

cusum_symm_tensor <- function(z) {
    .Call(`_SpecCp_cusum_symm_tensor`, z)
}

cusum_vec <- function(z) {
    .Call(`_SpecCp_cusum_vec`, z)
}

mysd <- function(x) {
    .Call(`_SpecCp_mysd`, x)
}

powerIteration0 <- function(X, k, v1_init = NULL, max_iter = 10L, lambda_diff_threshold = 1e-06, trace = FALSE) {
    .Call(`_SpecCp_powerIteration0`, X, k, v1_init, max_iter, lambda_diff_threshold, trace)
}

mytruncate <- function(x, s) {
    .Call(`_SpecCp_mytruncate`, x, s)
}

unfold_tnsr <- function(tnsr, mode) {
    .Call(`_SpecCp_unfold_tnsr`, tnsr, mode)
}

ttl_rcpp <- function(tnsr, list_mat, ms) {
    .Call(`_SpecCp_ttl_rcpp`, tnsr, list_mat, ms)
}

